<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OB-Nom34" failures="0" tests="1" name="LedgerCodeCTProfitLoss.TC7LedgerCode_CTAdjustment_ProfitLoss_CharitableDonations" time="108.337" errors="1" timestamp="2022-03-14T18:40:30 IST" skipped="0">
  <testcase classname="LedgerCodeCTProfitLoss.TC7LedgerCode_CTAdjustment_ProfitLoss_CharitableDonations" name="LedgerCode_CTAdjstment_ProfitLoss_CharitableDonations_Debit" time="108.337">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at page.factories.CT_Computation_Corporation_Tax.verifyTotalValue(CT_Computation_Corporation_Tax.java:193)
at page.factories.CT_Computation_Corporation_Tax.selectFinancialYear(CT_Computation_Corporation_Tax.java:128)
at LedgerCodeCTProfitLoss.TC7LedgerCode_CTAdjustment_ProfitLoss_CharitableDonations.LedgerCode_CTAdjstment_ProfitLoss_CharitableDonations_Debit(TC7LedgerCode_CTAdjustment_ProfitLoss_CharitableDonations.java:175)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- LedgerCode_CTAdjstment_ProfitLoss_CharitableDonations_Debit -->
  <system-out/>
</testsuite> <!-- LedgerCodeCTProfitLoss.TC7LedgerCode_CTAdjustment_ProfitLoss_CharitableDonations -->
